### ISSUE TITLE
mosesphrasetable2alignmodel stumbles over some input in phrasetable?

### ISSUE THREAD

**Issue by proycon** [proycon/colibri-mt#1]
```
Starting program: /scratch2/www/lamachine/bin/colibri-mosesphrasetable2alignmodel -i /vol/tensusers/proycon/colloquery/opensubtitles2012.nl-en.phrasetable -o /scratch/proycon/tmp/alignmodel.colibri -S /scratch/proycon/tmp/opensubtitles2012.nl.colibri.cls -T /scratch/proycon/tmp/opensubtitles2012.en.colibri.cls -m /scratch/proycon/tmp/opensubtitles2012.nl.colibri.patternmodel -M /scratch/proycon/tmp/opensubtitles2012.en.colibri.patternmodel -t 4 -l 8 -p 0.2 -P 0.2 -j 0 -d 0.05
Loading source encoder /scratch/proycon/tmp/opensubtitles2012.nl.colibri.cls
Loading target encoder /scratch/proycon/tmp/opensubtitles2012.en.colibri.cls
Loading source constraint model /scratch/proycon/tmp/opensubtitles2012.nl.colibri.patternmodel
Loading /scratch/proycon/tmp/opensubtitles2012.nl.colibri.patternmodel
(Loaded 27020041 patterns)
Loading target constraint model /scratch/proycon/tmp/opensubtitles2012.en.colibri.patternmodel
Loading /scratch/proycon/tmp/opensubtitles2012.en.colibri.patternmodel
(Loaded 35211726 patterns)
Loading moses phrasetable /vol/tensusers/proycon/colloquery/opensubtitles2012.nl-en.phrasetable
(Inferring extra contraints from source model, for faster discarding of patterns)
(added 226415 unigrams)
terminate called after throwing an instance of 'UnknownTokenError'
  what():  The input contained an unknown token

Program received signal SIGABRT, Aborted.
0x00002aaaab97ec37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00002aaaab97ec37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00002aaaab982028 in __GI_abort () at abort.c:89
#2  0x00002aaaab188535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00002aaaab1866d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00002aaaab186703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00002aaaab186922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00002aaaaace40be in ClassEncoder::encodestring (this=this@entry=0x7fffffffd5a0, line="! \" \" no , we 're", 
    outputbuffer=outputbuffer@entry=0x2aaaaaef46e0 <buildbuffer> "$gg\243\036\a\026\356R\263Z\b", allowunknown=allowunknown@entry=false, autoaddunknown=autoaddunknown@entry=false, 
    nroftokens=nroftokens@entry=0x0) at classencoder.cpp:414
#7  0x00002aaaaace4258 in ClassEncoder::buildpattern (this=this@entry=0x7fffffffd5a0, patternstring="! \" \" no , we 're", allowunknown=allowunknown@entry=false, 
    autoaddunknown=autoaddunknown@entry=false) at classencoder.cpp:435
#8  0x000000000040658b in loadmosesphrasetable (model=..., filename="/vol/tensusers/proycon/colloquery/opensubtitles2012.nl-en.phrasetable", sourceencoder=..., targetencoder=..., 
    constrainsourcemodel=constrainsourcemodel@entry=0x617810, constraintargetmodel=constraintargetmodel@entry=0x3b04060, max_sourcen=8, pts=pts@entry=0.20000000000000001, 
    pst=pst@entry=0.20000000000000001, joinedthreshold=joinedthreshold@entry=0, divergencefrombestthreshold=divergencefrombestthreshold@entry=0.050000000000000003, delimiter="|||", 
    score_column=score_column@entry=3, pstfield=pstfield@entry=0, ptsfield=ptsfield@entry=2, maxscores=maxscores@entry=10) at mosesphrasetable2alignmodel.cpp:202
#9  0x0000000000403d65 in main (argc=<optimized out>, argv=<optimized out>) at mosesphrasetable2alignmodel.cpp:381
```

**Comment by proycon** [comment]
source and target were reversed in the calling application, causing all the mismatches.
